[package]
name = "multi-layer_network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
csv = "1.1.6"
rand = "0.8.5"
plotters = "0.3.2"
chronometer = "0.1.2"
